sudo: false
language: python
python: 
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5

cache:
  # must specify pip dir
  # https://github.com/travis-ci/travis-ci/issues/3239
  directories:
    - $HOME/.cache/pip

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

# Install numpy, then BioPython and other dependencies
# BioPython doesn't always play well with pip install.
before_install: 
  - pip wheel pandas sqlalchemy decorator biopython
# for tox
  - pip wheel check-manifest readme_renderer flake8 tox

install: 
  - pip install .
  - pip install tox

script: tox

notifications:
  email:
    - crosenth@uw.edu
